# Generated by Django 4.1.7 on 2023-03-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
