# Generated by Django 4.1.7 on 2023-03-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=18)),
                ('pin_number', models.IntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
